name: Actions 
on:
  push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -cover -v ./...
